"use client";
import Link from "next/link";
import { BarChart3, BookOpen, CalendarCheck2, ChevronRight, GraduationCap, LayoutDashboard, Menu, MessageSquare, Search, Settings, Sparkles, UserPlus, Users, X, LogOut } from "lucide-react";
import { useState } from "react";

const items=[
  ["Overview","/dashboard",LayoutDashboard], ["Classrooms","/classrooms",BookOpen], ["Students","/students",Users], ["Admissions","/admissions",UserPlus], ["Attendance","/attendance",CalendarCheck2], ["Courses","/courses",BookOpen], ["Grades","/grades",BarChart3], ["Messages","/messages",MessageSquare], ["AI insights","/insights",Sparkles]
] as const;

export function WorkspaceShell({children,title="Overview",subtitle="School workspace"}:{children:React.ReactNode;title?:string;subtitle?:string}){
 const [open,setOpen]=useState(false); const [q,setQ]=useState("");
 return <div className="noise min-h-screen bg-[var(--bg)] text-[var(--text)]"><div className="flex min-h-screen">
  {open&&<button aria-label="Close navigation" onClick={()=>setOpen(false)} className="fixed inset-0 z-40 bg-black/60 lg:hidden"/>}
  <aside className={`fixed inset-y-0 left-0 z-50 flex w-[248px] flex-col border-r hairline bg-[#0b0d0c] px-3 py-4 transition-transform duration-200 lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}>
   <div className="flex items-center justify-between px-2 pb-5"><Link href="/" className="flex items-center gap-2.5 text-sm font-semibold tracking-[-.03em]"><span className="grid size-8 place-items-center rounded-lg bg-[#f2f1eb] text-[#090a0a]"><GraduationCap size={16}/></span>Student OS</Link><button onClick={()=>setOpen(false)} className="rounded-md p-2 text-[var(--muted)] lg:hidden"><X size={16}/></button></div>
   <div className="mx-2 mb-3 flex items-center justify-between rounded-lg border hairline bg-white/[.025] px-3 py-2"><div><p className="text-[10px] font-medium text-[var(--soft)]">Barnala Campus</p><p className="mono mt-0.5 text-[8px] text-[var(--muted)]">ADMIN / LIVE</p></div><ChevronRight size={13} className="text-[var(--muted)]"/></div>
   <p className="px-3 pb-2 pt-3 text-[9px] font-semibold uppercase tracking-[.16em] text-[#666b65]">Workspace</p>
   <nav className="space-y-0.5">{items.map(([label,href,Icon])=>{const active=title.toLowerCase().includes(label.split(" ")[0].toLowerCase());return <Link key={href} href={href} onClick={()=>setOpen(false)} className={`group flex items-center gap-3 rounded-lg px-3 py-2.5 text-[11px] font-medium transition-colors duration-150 ${active?"bg-white/[.09] text-[var(--text)]":"text-[#858b84] hover:bg-white/[.045] hover:text-[var(--text)]"}`}><Icon size={15} strokeWidth={1.8}/><span>{label}</span>{label==="Messages"&&<span className="ml-auto grid size-4 place-items-center rounded-full bg-[#9aa887] text-[8px] font-bold text-[#10120f]">3</span>}</Link>})}</nav>
   <div className="mt-auto border-t hairline pt-3"><Link href="#settings" className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-[11px] text-[#858b84] hover:bg-white/[.045] hover:text-white"><Settings size={15}/> Settings</Link><Link href="/" className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-[11px] text-[#858b84] hover:bg-white/[.045] hover:text-white"><LogOut size={15}/> Exit workspace</Link></div>
  </aside>
  <section className="min-w-0 flex-1"><header className="glass sticky top-0 z-30 border-b hairline"><div className="flex h-[64px] items-center gap-3 px-4 sm:px-7 lg:px-9"><button onClick={()=>setOpen(true)} className="rounded-lg border hairline bg-white/[.03] p-2 text-[var(--soft)] lg:hidden"><Menu size={17}/></button><div className="hidden min-w-0 sm:block"><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#666b65]">{subtitle}</p><h1 className="mt-0.5 truncate text-sm font-medium tracking-[-.02em]">{title}</h1></div><div className="relative ml-auto w-full max-w-sm"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#666b65]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search anything…" className="w-full rounded-lg border hairline bg-white/[.035] py-2.5 pl-9 pr-12 text-[11px] text-white outline-none placeholder:text-[#60655f] focus:border-white/20"/><kbd className="absolute right-2 top-1/2 hidden -translate-y-1/2 rounded border hairline px-1.5 py-0.5 text-[8px] text-[#696e68] sm:block">⌘ K</kbd></div><button className="relative rounded-lg border hairline bg-white/[.03] p-2.5 text-[#a0a49e] hover:text-white"><span className="absolute right-2 top-2 size-1.5 rounded-full bg-[#9aa887] breathe"/><MessageSquare size={15}/></button><div className="hidden items-center gap-2 border-l hairline pl-4 md:flex"><div className="grid size-7 place-items-center rounded-full bg-[#aab49b] text-[10px] font-semibold text-[#172018]">A</div><div><p className="text-[10px] font-medium">Admin</p><p className="text-[8px] text-[#666b65]">School administrator</p></div></div></div></header><main className="mx-auto max-w-[1440px] px-4 py-7 sm:px-7 lg:px-9 lg:py-9">{children}</main></section>
 </div></div>
}
