"use client";
import { useMemo, useState } from "react";
import { ArrowUpRight, BarChart3, CalendarCheck2, Check, ChevronRight, Clock3, Sparkles, Users } from "lucide-react";
import { WorkspaceShell } from "@/components/workspace-shell";

const activities=[["Attendance recorded","12-A · Physics","08:42","good"],["Marks updated","11-B · Mathematics","09:18","neutral"],["New profiles","12 students awaiting review","10:04","warn"],["Assignment submitted","Aarav · Physics Lab","10:26","neutral"]] as const;
const classes=[["12-A","Physics","31 / 34","91%"],["11-B","Mathematics","28 / 30","93%"],["10-C","Chemistry","26 / 29","90%"],["12-B","Computer Science","29 / 31","94%"]] as const;

export default function DashboardPage(){const [range,setRange]=useState("This week");const [done,setDone]=useState<string[]>([]);const [query]=useState("");const filtered=useMemo(()=>classes.filter(x=>x.join(" ").toLowerCase().includes(query.toLowerCase())),[query]);return <WorkspaceShell title="Overview" subtitle="Monday · 24 August 2026"><div className="rise">
 <div className="flex flex-col gap-5 border-b hairline pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="mono text-[9px] uppercase tracking-[.14em] text-[#70766f]">Command center / 01</p><h2 className="mt-2 text-[34px] font-medium leading-none tracking-[-.055em] sm:text-[48px]">Good morning, Admin.</h2><p className="mt-3 max-w-lg text-[12px] leading-6 text-[#8f948d]">A calm view of the school: what needs attention, what is moving, and what changed since yesterday.</p></div><div className="flex items-center gap-2"><div className="flex rounded-lg border hairline bg-white/[.025] p-1">{["Today","This week","Term"].map(x=><button key={x} onClick={()=>setRange(x)} className={`rounded-md px-3 py-1.5 text-[9px] font-medium transition ${range===x?"bg-white/[.1] text-white":"text-[#70766f] hover:text-white"}`}>{x}</button>)}</div><button className="grid size-9 place-items-center rounded-lg bg-[#e7eadf] text-[#151914] transition hover:scale-[1.03]"><ArrowUpRight size={15}/></button></div></div>
 <div className="mt-6 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{[["Attendance","92.4%","+2.1%","#75b798",CalendarCheck2],["Students","1,247","+12 this week","#9aa887",Users],["Classes","36","8 active now","#737fe5",BarChart3],["Avg. score","84.7%","+4.8% term","#c6a878",Sparkles]].map(([label,value,delta,color,Icon])=><div key={label as string} className="group relative overflow-hidden rounded-xl border hairline bg-white/[.025] p-4 transition duration-200 hover:-translate-y-0.5 hover:bg-white/[.04]"><div className="flex items-center justify-between"><span className="text-[10px] text-[#858b84]">{label as string}</span><span className="grid size-7 place-items-center rounded-md bg-white/[.045]" style={{color:color as string}}><Icon size={14}/></span></div><p className="mt-5 text-[27px] font-medium tracking-[-.05em]">{value as string}</p><p className="mt-1 text-[9px] text-[#70766f]">{delta as string}</p></div>)}</div>
 <div className="mt-5 grid gap-3 xl:grid-cols-[1.35fr_.65fr]"><section className="overflow-hidden rounded-xl border hairline bg-white/[.02]"><div className="flex items-center justify-between border-b hairline px-5 py-4"><div><p className="mono text-[8px] uppercase tracking-[.14em] text-[#666c65]">Live register</p><h3 className="mt-1 text-sm font-medium">Today&apos;s classes</h3></div><span className="flex items-center gap-1.5 text-[9px] text-[#858b84]"><i className="breathe size-1.5 rounded-full bg-[#75b798]"/> 36 classes</span></div><div className="divide-y hairline">{filtered.map(([name,subject,present,rate])=><div key={name} className="group flex items-center gap-4 px-5 py-4 transition hover:bg-white/[.025]"><div className="grid size-9 place-items-center rounded-lg border hairline bg-white/[.025] text-[10px] font-medium">{name}</div><div className="min-w-0 flex-1"><p className="text-[11px] font-medium">{subject}</p><p className="mt-0.5 text-[9px] text-[#6f756e]">{present} present</p></div><div className="hidden w-24 sm:block"><div className="h-1 rounded-full bg-white/[.07]"><div className="h-1 rounded-full bg-[#9aa887]" style={{width:rate}}/></div></div><span className="mono text-[9px] text-[#aeb2aa]">{rate}</span><ChevronRight size={13} className="text-[#555b55] transition group-hover:translate-x-0.5 group-hover:text-white"/></div>)}</div></section><section className="relative overflow-hidden rounded-xl border hairline bg-[#111411] p-5"><div className="absolute -right-16 -top-16 size-40 rounded-full bg-[#9aa887]/10 blur-3xl"/><div className="relative flex items-center justify-between"><span className="grid size-8 place-items-center rounded-lg bg-white/[.06] text-[#aab59b]"><Sparkles size={15}/></span><span className="mono text-[8px] text-[#666c65]">SIGNAL / 03</span></div><h3 className="relative mt-14 max-w-xs text-[22px] font-medium leading-tight tracking-[-.04em]">Your school is moving in the right direction.</h3><p className="relative mt-3 text-[10px] leading-5 text-[#747a73]">Attendance is up 2.1% and average performance is up 4.8% this term.</p><button className="relative mt-6 flex items-center gap-2 rounded-lg bg-[#e7eadf] px-3.5 py-2.5 text-[10px] font-semibold text-[#141713] transition hover:-translate-y-0.5">Open insights <ChevronRight size={13}/></button></section></div>
 <div className="mt-3 grid gap-3 lg:grid-cols-[1fr_1fr]"><section className="rounded-xl border hairline bg-white/[.02] p-5"><div className="flex items-center justify-between"><div><p className="mono text-[8px] uppercase tracking-[.14em] text-[#666c65]">Activity</p><h3 className="mt-1 text-sm font-medium">Latest changes</h3></div><Clock3 size={14} className="text-[#666c65]"/></div><div className="mt-4 divide-y hairline">{activities.map(([a,b,t,s],i)=><div key={a} className="flex items-center gap-3 py-3 first:pt-1"><span className={`grid size-7 place-items-center rounded-md ${s==='good'?'bg-[#75b798]/10 text-[#75b798]':s==='warn'?'bg-[#c6a878]/10 text-[#c6a878]':'bg-white/[.045] text-[#8e948d]'}`}><Check size={13}/></span><div className="min-w-0 flex-1"><p className="text-[10px] font-medium">{a}</p><p className="truncate text-[8px] text-[#686e67]">{b}</p></div><span className="mono text-[8px] text-[#5f655e]">{t}</span></div>)}</div></section><section className="rounded-xl border hairline bg-white/[.02] p-5"><div className="flex items-center justify-between"><div><p className="mono text-[8px] uppercase tracking-[.14em] text-[#666c65]">Review queue</p><h3 className="mt-1 text-sm font-medium">Needs attention</h3></div><span className="grid size-6 place-items-center rounded-full bg-[#c6a878]/10 text-[9px] font-medium text-[#c6a878]">18</span></div><div className="mt-4 space-y-2">{[["12 students","Attendance below 80%"],["3 classes","Attendance not submitted"],["3 submissions","Assignments need grading"]].map(([a,b])=><button key={a} onClick={()=>setDone([...done,a])} className={`flex w-full items-center justify-between rounded-lg border hairline px-3.5 py-3 text-left transition hover:bg-white/[.03] ${done.includes(a)?"opacity-40":""}`}><span><span className="block text-[10px] font-medium">{a}</span><span className="mt-0.5 block text-[8px] text-[#686e67]">{b}</span></span><ChevronRight size={13} className="text-[#60665f]"/></button>)}</div></section></div>
 </div></WorkspaceShell>}
